### ISSUE TITLE
Can someone publish the latest version(0.2.0) to ruby gems please

### ISSUE THREAD

**Issue by suryaiscrazy** [reevoo/pact-messages#5]
@amalkov , can you please push this to rubygems.org.

**Comment by palin** [comment]
@suryaiscrazy done

**Comment by palin** [comment]
sorry, I pushed to our /gems, is it OK?

**Comment by suryaiscrazy** [comment]
I was hoping we could have the new version out on rubygems

**Comment by suryaiscrazy** [comment]
@davidsevcik or @amalkov , can you please publish 0.2.0 when you have some time

**Comment by RaVbaker** [comment]
please do it to ruby gems 🙏  @palin

**Comment by mycargus** [comment]
0.2.0 on ruby gems would be great to have, please 😃 Thanks for your work!

**Comment by amalkov** [comment]
done, sorry for the delay

**Comment by suryaiscrazy** [comment]
Thank you :)
